spring:
  datasource:
    url: jdbc:h2:mem:rst;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop

app:
  security:
    dev-identity:
      ccgid: SUPERVISOR001
      role: SUPERVISOR
      agent-ccgid: AGENT001
